version: '3.8'

services:
  exxahub_backtest_api:
    build: .
    container_name: exxahub_backtest_api
    ports:
      - "3000:3000"
    networks:
      - exxahub_network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "./src/api/index.ts", "--watch", "./src/"]

  exxahub_backtest_migrations:
    build: .
    container_name: exxahub_backtest_migrations
    depends_on:
      exxahub_backtest_db:
        condition: service_healthy
    networks:
      - exxahub_network
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: ["bun", "run", "migrate:latest"]

  exxahub_backtest_db:
    image: 'postgres:16.4-alpine3.20'
    container_name: exxahub_backtest_db
    ports:
      - "5433:5432"
    networks:
      - exxahub_network
    environment:
        PGPASSWORD: '${DB_PASS}'
        POSTGRES_DB: '${DB_NAME}'
        POSTGRES_USER: '${DB_USER}'
        POSTGRES_PASSWORD: '${DB_PASS}'
    volumes:
        - 'db:/var/lib/postgresql/data'
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
        interval: 1s
        timeout: 1s
        retries: 10

networks:
  exxahub_network:
    external: true

volumes:
  db:
    driver: local